### ISSUE TITLE
Parametrization

### ISSUE THREAD

**Issue by ionelmc** [jonparrott/nox#1]
Building a bit on https://www.reddit.com/r/Python/comments/48qz7w/nox_virtualenvtest_automation_similar_to_tox_but/d0m3q4l, another way to handle parametrization is like this:
```python
@nox.parametrize('python', ['/path/to/python2.7', '/path/to/python3.5', '/path/to/pypy', ...], ids=['py27', 'py34', 'pypy', ...])
@nox.parametrize('django', ['1.9', '1.8', ...])
def session_test(session, python, django):
   ...
```

This is quite identical to [pytest parametrization](http://pytest.org/latest/parametrize.html?highlight=parametrize). 

The advantage over your initial proposal is that you can customize the display names (via `ids`).

Also, would be good to know how far and where you'd take nox. IOW, what goals does nox have? 

PS. There is no contribution guide.

**Comment by jonparrott** [comment]
Filed #2 for the contribution guide.

I'd definitely like to match `py.test`'s parameterization as much as possible. I need to dig into how they implement it, but if you have any ideas I'd be happy to hear them.

> Also, would be good to know how far and where you'd take nox. IOW, what goals does nox have?

I made nox to solve some pain points with a couple of projects where tox was unwieldy. I think a reasonable goal to start with is to have parity with tox with python configuration files instead of ini configuration files (and less 'magic'). But I'm 100% open to any feature suggestions.

**Comment by ionelmc** [comment]
Are you looking towards having 1:1 feature parity with tox? (all those weird options like `use_develop`, `skip_sdist` etc)

**Comment by jonparrott** [comment]
I would say it's at a higher level than that. I don't necessary want a `session.skip_sdist` or `session.use_develop` option - I just want those things to be easily possible in nox. Those two, for example, already are possible as you're in complete control of whether or not to run `pip install -e .` or whatever.

**Comment by jonparrott** [comment]
Okay, looks like the easiest way to do this is to just write a decorator that adds a `calls` attribute to the function, then have the loader expand those calls into individual test functions.

**Comment by jonparrott** [comment]
@ionelmc how important is the ability to stack the decorator?

**Comment by jonparrott** [comment]
Nevermind, I figured it out. :)

**Comment by ionelmc** [comment]
I usually need multi tier parametrization and I've used a configuration file and a template to generate `tox.ini`. It's not very pretty. You can see it here: https://github.com/ionelmc/python-manhole/blob/master/setup.cfg#L42-L94

The point is this parametrization should allow multiple variables, make a product and allow the user to skip some of the combinations programmatically.

**Comment by jonparrott** [comment]
Cool. I've got that worked out I just need to integrate the generated
functions with the session runner. Stay tuned. :)
