### ISSUE TITLE
Windows interpreters

### ISSUE THREAD

**Issue by lukesneeringer** [jonparrott/nox#17]
Using nox on Windows with custom interpreters fails, because the virtualenv is passed `-p pythonX.Y`, and that is not the correct thing on Windows.

I am not entirely sure what the right way to handle this is. Tox does [this][1], which nox could basically port into nox. (Nox already has a `which` function, but it does a subset of this, expects a path, and also does not run on virtualenv creation.)

Alternatively, nox could expose a function (e.g. `nox.path.resolve(maj, min)` that would return the appropriate string, which would have to be manually called and assigned to `session.interpreter`. That would make this behavior explicitly opt-in.

This can be worked around in nox now (since `nox.py` is a Python script), but is painful for my use case because I would have to copy this to tons of files. Thoughts?

  [1]: https://github.com/tox-dev/tox/blob/master/tox/interpreters.py#L126-L173

**Comment by jonparrott** [comment]
Yeah, let's do it, let's port the subset of tox's logic that we need.

**Comment by lukesneeringer** [comment]
That will require getting AppVeyor working again. Any clue what it is complaining about? (Is it complaining because Unicode strings are being set as environment variables, perchance?)

**Comment by lukesneeringer** [comment]
This is in-progress on [this branch][1]; trying to prove it actually works before writing tests and making a PR.

  [1]: https://github.com/lukesneeringer/nox/tree/windows

**Comment by lukesneeringer** [comment]
#18 is merged.
