### ISSUE TITLE
Allow configuration of virtualenv names

### ISSUE THREAD

**Issue by tseaver** [jonparrott/nox#25]
Hashing the virtualenv names makes it inconvenient to spelunk into them later,  I would find it more useful to allow for customizing names for too-long session virtualenvs.

**Comment by jonparrott** [comment]
Not sure if this is the right solution to the problem, as even with a custom name if you run nox from a long enough absolute path it'll still fail.

Does ``--envdir`` help? What more should we do?

**Comment by tseaver** [comment]
My `nox.py` looks like:

```python
@nox.session
@nox.parametrize('python_version', ['2.7', '3.4', '3.5', '3.6'])
def unit_tests(session, python_version):
    """Run the unit test suite."""
    ...
```

```bash
$ nox --envdir /tmp/nox-25/
nox > Running session unit_tests(python_version='2.7')
nox > virtualenv /tmp/nox-25/unit_tests-python_version-2-7 -p python2.7
...
```

In my "normal" location, the session virtualenv gets hashed to an 8-character name.  If I could manually configure it, I would use something like `u-py27`, which would be even shorter.

**Comment by jonparrott** [comment]
Any ideas on how to deal with parametrize and custom names?

**Comment by lukesneeringer** [comment]
How about

```python
session.env_name = 'unit-py{0}'.format(python_version)
```

**Comment by jonparrott** [comment]
Sounds reasonable to me. If anyone wants to take this on before I get a chance to, just let me know.

**Comment by lukesneeringer** [comment]
I might be able to knock it out, but no worries if you get there before I do.

**Comment by jonparrott** [comment]
Added in 48bd094
