### ISSUE TITLE
Python files break directory parametization

### ISSUE THREAD

**Issue by waprin** [jonparrott/nox#26]
As mentioned offline, 

```
@nox.parametrize('sample', ALL_SAMPLE_DIRECTORIES)
def session_lint(session, sample):
    """Runs flake8 on the sample."""
    session.install('flake8', 'flake8-import-order')
```
not all sessions are getting found if there's another Python file in same directory as nox.

Not a big deal, just creating tracking issue.

**Comment by jonparrott** [comment]
This belongs over at python-docs-samples, as it's just related to the logic that figures out `ALL_SAMPLE_DIRECTORIES`.
