### ISSUE TITLE
Migration from tox.ini

### ISSUE THREAD

**Issue by ionelmc** [jonparrott/nox#3]
Just putting this out here for consideration.

It would be nice if there was some tool that could convert `tox.ini` to a `nox.py`.

This would mean there needs to be some feature parity with tox (related: https://github.com/jonparrott/nox/issues/1#issuecomment-191865981)

For me this isn't so important but it would help with nox's adoption I think.

**Comment by jonparrott** [comment]
I agree. I think at minimal we should have a section in the docs on `migrating from tox`.

`tox.ini` files can be crazy, so I'm unsure about parsing them and spitting out a `nox.py`, but I think once we have some documentation in place we can look into it.

**Comment by jonparrott** [comment]
Added basic support in 4fe199a, see http://nox.readthedocs.io/en/latest/usage.html#converting-from-tox

**Comment by dhermes** [comment]
Ooooooh fancy!
