### ISSUE TITLE
Publish changelog

### ISSUE THREAD

**Issue by tseaver** [jonparrott/nox#31]
Readers need to find the changes, ideally in the docs.  If not, then the minimum would be to annotate the tags here on Github into actual releases documenting bugs fixed, features added, and particularly backward incompatibilities.

**Comment by jonparrott** [comment]
Totally fair. I'd planned on doing this once I settled on an interface as
there was a lot of churn in the early versions. I think we can probably
call the current version 1.0 as it seems it's been pretty stable for a bit.
We can start the changelog there.

**Comment by jonparrott** [comment]
Resolved by #50.
