### ISSUE TITLE
Support a "presession"/"postsession" session

### ISSUE THREAD

**Issue by duggelz** [jonparrott/nox#42]
This is a somewhat half-baked idea.  For the google-cloud-python config, we have a parametrized 'tests' session, that collects coverage information over several different parametrized runs, and a non-parametrized 'cover' session that collects everything and creates a single coverage report.  It would be nice if we could make some function or session that runs once after every 'tests' session is done, so that 'nox -s tests' produces the coverage report by itself.

This could be done really grossly by a variety of means: Giving the 'cover' session a mangled name like 'tests_post', adding a new kind of 'parametrize' that just appends a single new session instead of doing an MxN product of all previous parameters, or passing in a 'is_last_parameter' to the tests session.

This can be done right now by something like:

```
@nox.session
@nox.parametrize('version', ['2.7', '3.4', '3.5', '3.6'])
@nox.parametrize('subdir', ['runtime_builders','otherdir'])
@nox.parametrize('coverage_report', [False, True])
def tests(session, version, subdir, coverage_report):
  if not coverage_report:
    .. do normal tests
  elif version == '2.7' and subdir == 'runtime_builders': # FRAGILE
    .. produce coverage report
```

**Comment by jonparrott** [comment]
I wonder how this fits into @lukesneeringer's idea for `session.notify`?

**Comment by jonparrott** [comment]
I'm going to close this, as I feel the `notify` functionality accommodates this. We can continue discussing if it doesn't.
