### ISSUE TITLE
Use virtualenv from the current Python running nox

### ISSUE THREAD

**Issue by dhermes** [jonparrott/nox#45]
... rather than just getting `virtualenv` from `PATH`.

As @jonparrott [mentioned][1]

> This would be pretty straightforward, we should just invoke `python -m virtualenv`

(#44 was originally titled this, but I accidentally repurposed that issue)

[1]: https://github.com/jonparrott/nox/issues/44#issuecomment-330067012

**Comment by jonparrott** [comment]
Does this actually solve the issue in #44 or should we just do this anyway?

**Comment by jonparrott** [comment]
Also - since we specify the interpreter to virtualenv does this even matter?

**Comment by jonparrott** [comment]
(FYI it seems [tox does this](https://github.com/tox-dev/tox/blob/master/tox/venv.py#L429)).

**Comment by dhermes** [comment]
> since we specify the interpreter to virtualenv does this even matter?

Sort of. Hypothetical:

- `PATH=/opt/a/bin:/opt/b/bin`
- `nox` is installed in only one place `/opt/b/bin/nox`
- `virtualenv` is installed in two places `/opt/a/bin/virtualenv` and `/opt/b/bin/virtualenv`
- `/opt/a/bin/virtualenv` (the one that wins on `PATH`) is old and broken somehow
- `/opt/b/bin/virtualenv` is new and updated (from the same shiny environment that `nox` is installed into)

In the current incantation, the broken `virtualenv` would get used with `nox`.
