### ISSUE TITLE
Locate Python interpreters on Windows via the `py.exe` launcher

### ISSUE THREAD

**Issue by pfmoore** [jonparrott/nox#46]
On Windows, the versioned Python executables (`python3.6` and similar) don't exist. So to set a specific interpreter needs a hard-coded path (as far as I can tell from some simple experiments). The nox code says that it is based on the `tox` code, but it omits the `locate_via_py` step in tox that uses the `py.exe` launcher to resolve names like `python3.6`.

Could this be added, as the "standard" location is wrong for Python 3.6+, and if the user overrides the standard location, the current nox code won't handle this whereas the launcher will?

I'm willing to try to put together a PR if needed.

**Comment by jonparrott** [comment]
> Could this be added, as the "standard" location is wrong for Python 3.6+, and if the user overrides the standard location, the current nox code won't handle this whereas the launcher will?

I'm absolutely open to this. Although from my experiments on Windows what we have now seems to work (at least in AppVeyor) - but of course edge cases abound.

> I'm willing to try to put together a PR if needed.

That would be awesome. :)

**Comment by pfmoore** [comment]
Yeah, the "standard locations" you use are exactly what Appveyor uses (they aren't completely standard for the python.org installers, though). I'll see what I can do for a PR.

**Comment by jonparrott** [comment]
Thanks, @pfmoore. :) If you can't do a PR, maybe just linking us to some docs on how the `py.exe` launcher works would be helpful.

**Comment by pfmoore** [comment]
I've submitted #53, but there are a few outstanding questions, which I've noted in a comment there. I'd appreciate your input. (I have manually tested the change locally, and confirmed it works).

**Comment by dhermes** [comment]
This seems fixed? Though the question of how to locate the 32-bit interpreters is still open.
