### ISSUE TITLE
Importing issues w/ nox.py

### ISSUE THREAD

**Issue by di** [jonparrott/nox#61]
I feel like I'm missing something obvious, but the recommendation to put configuration in a `nox.py` file isn't working for me (at least on my system).

Using the example from the docs:
```
$ cat nox.py
import nox

@nox.session
def tests(session):
    session.install('py.test')
    session.run('py.test')

@nox.session
def lint(session):
    session.install('flake8')
    session.run('flake8', '--import-order-style', 'google')
```

And the latest version:
```
$ pip freeze | grep nox
nox-automation==0.18.1
```

This is what I get:
```
$ nox
Traceback (most recent call last):
  File "/private/tmp/env/bin/nox", line 7, in <module>
    from nox.main import main
  File "/private/tmp/nox.py", line 3, in <module>
    @nox.session
AttributeError: module 'nox' has no attribute 'session'
```

As far as I'm aware this is the expected importing behavior when a local file shadows a 3rd party module... what am I missing?

**Comment by jonparrott** [comment]
Hrm, can you tell me your OS and which version of Python you're using?

**Comment by di** [comment]
Nothing fancy:

```
$ uname -a
Darwin di 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ python --version
Python 3.6.0
```

**Comment by jonparrott** [comment]
I feel like this came up before - are you sure that nox is installed in the same virtualenv where you're invoking it? For example, if you install nox globally then execute it in a virtualenv I think this can happen.

**Comment by di** [comment]
It seems like this was due to me having a funky `PYTHONPATH` that hasn't ever bitten me until now. E.g.:

```
$ export PYTHONPATH=:
$ nox
Traceback (most recent call last):
  File "/Users/di/.pyenv/versions/3.6.0/bin/nox", line 7, in <module>
    from nox.main import main
  File "/Users/di/git/python-packaging-user-guide/nox.py", line 11, in <module>
    @nox.session
AttributeError: module 'nox' has no attribute 'session'
$ export PYTHONPATH=
$ nox
nox > Running session tests
...
```
Sorry for the noise!

**Comment by jonparrott** [comment]
Yay it wasn't my fault. :)
