### ISSUE TITLE
nox start up errors

### ISSUE THREAD

**Issue by chemelnucfin** [jonparrott/nox#76]
I don't know what I did, but I can't start nox any more.
I tried pip uninstall and then reinstalling
I tried restarting the computer (using Ubuntu 16.04)

This file has 0 bytes, ~/.local/venvs/nox-automation/bin/python
and I tried substituting that with #!usr//bin/python

This is the error message that I get
`from: can't read /var/mail/nox.main`
`~/.local/bin/nox:10: syntax error near unexpected token `('`

`~/.local/bin/nox:10: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'

Any other suggestions?
Thanks.

**Comment by dhermes** [comment]
@chemelnucfin Can you do two things:

- `which nox`
- `ls nox.py` in the directory that it is failing

**Comment by chemelnucfin** [comment]
~/.local/bin/nox
nox.py

But google-cloud-python and the subdirectories all have the same problem.

**Comment by dhermes** [comment]
- Is `~/.local/bin/nox` a symlink to anything? (`ls -alFG ~/.local/bin/nox`)
- Have you modified any of the `nox.py` files in `google-cloud-python` or are they the same as what is checked in to `master`?

Also, I don't think `nox` is broken, so we should probably close this issue and just chat in Hangouts?

**Comment by chemelnucfin** [comment]
symlink to ~/.local/venvs/nox-automation/bin/nox

I have modified the files, but usually just to run different tests.

I don't think it's a nox issue, but I'm not sure what changed and was just looking for suggestions on how to fix it if pip remove and pip install doesn't fix it.

**Comment by dhermes** [comment]
It's not as simple as "pip remove and pip install" since you have it in a virtual environment.

**Comment by chemelnucfin** [comment]
Thanks to @dhermes, the problem is resolved.

Somehow I guess nox was installed while I was in virtualenv when I first started, and maybe somehow the environment got corrupted?  Solution ended up erasing the venv directory and start fresh.
