### ISSUE TITLE
`tox-to-nox` is missing dependencies (tox, jinja2) for v0.18.2

### ISSUE THREAD

**Issue by vlcinsky** [jonparrott/nox#87]
Just installed `nox` and learned, that extra `tox-to-nox` is not provided any more.

It was nice to find out, it is already included, but running it fails with complains about missing `jinja2` and then `tox` dependencies.

After installing these dependencies, the `tox-to-nox` command worked well.

Consider adding the `jinja2` and `tox` to packages being required (and installed) by the package.

**Comment by jonparrott** [comment]
Hrm, the dependencies are listed here: https://github.com/jonparrott/nox/blob/master/setup.py#L76

If you `pip install nox[tox_to_nox]` you should get them.

**Comment by jonparrott** [comment]
Ha, it seems that pipsi ignores the error:

```
pipsi install nox-automation[tox-to_nox]
Already using interpreter /Users/jonwayne/.pyenv/versions/2.7.13/bin/python2.7
New python executable in /Users/jonwayne/.local/venvs/nox-automation/bin/python2.7
Also creating executable in /Users/jonwayne/.local/venvs/nox-automation/bin/python
Installing setuptools, pip, wheel...done.
Collecting nox-automation[tox-to_nox]
  Using cached nox_automation-0.18.2-py2.py3-none-any.whl
  nox-automation 0.18.2 does not provide the extra 'tox-to_nox'
Collecting six<2.0.0,>=1.4.0 (from nox-automation[tox-to_nox])
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting py<2.0.0,>=1.4.0 (from nox-automation[tox-to_nox])
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting virtualenv>=14.0.0 (from nox-automation[tox-to_nox])
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Collecting colorlog<3.0.0,>=2.6.1 (from nox-automation[tox-to_nox])
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from nox-automation[tox-to_nox])
  Using cached enum34-1.1.6-py2-none-any.whl
Installing collected packages: six, py, virtualenv, colorlog, enum34, nox-automation
Successfully installed colorlog-2.10.0 enum34-1.1.6 nox-automation-0.18.2 py-1.5.2 six-1.11.0 virtualenv-15.1.0
  Linked script /Users/jonwayne/.local/bin/nox
  Linked script /Users/jonwayne/.local/bin/tox-to-nox
Done.
```

Note that it says `nox-automation 0.18.2 does not provide the extra 'tox-to_nox'` but successful installs anyway. Looks like it's worth a bug report on pipsi?

> seeing the command tox-to-nox and expecting the extras to be named that style

Unfortunately extras can't contain `-`.

Closing, but let me know if there's anything else I can do. :)

**Comment by vlcinsky** [comment]
I would consider the warning message from pipsi enough care taken.

Thanks for really quick responses. And for making the nox - I am fan of tox (and pytest and doit) but nox impressed me today. I shall give it a try (on my Linux box but also on Windows boxes of my colleagues - I noticed some windows related issues and must be careful).

**Comment by jonparrott** [comment]
Great! Let us know if you run into anything. 

Nox *is* tested on Windows, so you should be fine there.
